### ISSUE TITLE
SKILL ISSUE

### ISSUE THREAD

**Issue by KrystofKavalir** [KrystofKavalir/projectWEA#2]
BRUH NIGA

**Comment by DexyHatesYou** [comment]
NIGGA YOU SUCK ASS

**Comment by DexyHatesYou** [comment]
FUCKING SKILL ISSUE NIGGA

**Comment by DexyHatesYou** [comment]
(to git mods, im black)

**Comment by DexyHatesYou** [comment]
WHHAT THE FUCK IS RACISMMMM RAHHH WE ONLY DONT LIKE CHOCO KFC EATERS

**Comment by DexyHatesYou** [comment]
**NIGGA YOU AINT BLOCKING SHIT** 
![image](https://github.com/KrystofKavalir/projectWEA/assets/73914078/5f052a9b-b5fa-4bf9-b201-a98e6a295707)
